version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: ocr-redis
    ports:
      - "6379:6379"

  ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env  # 👈 Ajouté ici
